In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.arange(10);
print(b)


[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
l=range(1000);
%timeit [i**2 for i in l]

358 µs ± 11.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a=np.arange(1000);
%timeit a**2

1.39 µs ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
#creating 1D array
a=np.array([1,2,3,4])
print(a)
print(a.size)
print(len(a))
print(a.shape)

#cretaing 2D array
b=np.array([[1,2,3],[4,5,6]])
print(b); #it prints the array 
print(b.size); #it prints the no. of element in the array
print(len(b)); #it prints the no of rows
print(b.shape); #it prints the shape of the array

#creating 3D array
c=np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])
print(c)
print(c.size)
print(len(c))
print(c.shape)

[1 2 3 4]
4
4
(4,)
[[1 2 3]
 [4 5 6]]
6
2
(2, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
2
(2, 2, 2)


In [19]:
#creating the array using arange funtion
d=np.arange(1,10,2)
print(d)

[1 3 5 7 9]


In [23]:
#creting the array using line space or linspace function
e=np.linspace(0,1,5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [32]:
# creating the unity matrix 
f1=np.ones(2) #1D
print(f1)
print("="*50)
f2=np.ones((2,2)) #2D
print(f2)
print("="*50)
f3=np.ones((2,2,2))
print(f3)
print("="*50)
f4=np.ones((2,2,2,2))
print(f4)


[1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


In [35]:
#printing zeros array/matrix/tensors
a1=np.zeros(2);
print(a1)
print("="*50)

a2=np.zeros((2,2));
print(a2)
print("="*50)

a3=np.zeros((2,2,2))
print(a3)


[0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [44]:
#printing identity matrix
b1=np.eye((2));
print(b1)
print("="*50)

b2=np.eye(3)
print(b2)
print("="*50)

b3=np.eye(2,3);
print(b3)
print("="*50)

b4=np.eye(3,4);
print(b4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [51]:
#printing diagonal matrix
t1=np.diag([1,2,3,4,5])
print(t1)
t1.dtype

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


dtype('int32')

In [50]:
t2=np.random.rand(2,5)
print(t2)
t2.dtype

[[0.90010045 0.63957016 0.17982555 0.46331551 0.510936  ]
 [0.51003736 0.8504777  0.84915096 0.92560766 0.96462582]]


dtype('float64')

In [52]:
t3=np.array([1+2j,2+4j])
print(t3)

[1.+2.j 2.+4.j]


In [53]:
t4=np.array([True,False,False,True])
print(t4)

[ True False False  True]


In [56]:
a=np.arange(10)
print(a[5])
print(a[:])
print(a[1::2])

5
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [57]:
b=np.arange(10);
print(b);
b[5:]=10
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 10 10 10 10 10]


In [58]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
b=a[::2]
print(b)

[0 2 4 6 8]


In [62]:
np.shares_memory(a,b)

True

In [63]:
c=a[::2].copy()
print(c)

[0 2 4 6 8]


In [64]:
np.shares_memory(a,c)

False

In [66]:
a=np.random.randint(1,10,15);
print(a)

[1 2 6 4 2 2 1 1 5 7 6 7 1 1 6]


In [75]:
a=np.diag([1,2,3,4])
print(a)
print('^'*50)
b=a*a
print(b)
print('='*50)
c=np.dot(a,a)
print(c)
print("*"*50)
d=a.dot(a)
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
**************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
